image: jazzypro/ubuntu-frontend:latest

stages:
  - analyze
  - build
  - deploy

analyze:
  stage: analyze
  script:
    - ansible-playbook ansible/analyze.yml
  only:
    - /^dev-.*$/
    - master
  allow_failure: true

build:
  stage: build
  script:
    - ansible-playbook ansible/build.yml
  artifacts:
    paths:
      - dist/
  only:
    - /^dev-.*$/
    - master

deploy-dev:
  stage: deploy
  script:
    - ansible-playbook ansible/deploy.yml
  dependencies:
    - build
  only:
    - master
    - /^dev-.*$/
  environment:
    name: $CI_BUILD_REF_NAME
    url: http://$CI_BUILD_REF_NAME.metasfresh.jzapp.io/
