image: jazzypro/ubuntu-frontend

stages:
  - build
  - deploy

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

build:
  stage: build
  script:
    - ci-run-local ansible/build.yml -v
  artifacts:
    paths:
      - dist/
  only:
    - dev
    - dev-189

deploy-dev:
  stage: deploy
  script:
    - ci-run-remote ansible/deploy.yml -v
  dependencies:
    - build
  only:
    - dev
    - dev-189
  environment: dev
