---
- hosts: localhost
  tasks:
    - name: Check if report dir exists
      stat:
        path: "{{ci.reports_dir}}/{{ci.ref_name}}"
      register: dir_check

    # create a base report for master if it deosn't exist
    - block:
      - name: Checkout base code version
        shell: "git checkout master"
        args:
          chdir: "{{ci.build_dir}}"
      - name: Create base report
        shell: "es6-plato -r -d {{ci.reports_dir}}/{{ci.ref_name}} ."
        args:
          chdir: "{{ci.build_dir}}"
      - name: Checkout current code version
        shell: "git checkout {{ci.ref_hash}}"
        args:
          chdir: "{{ci.build_dir}}"
      when: dir_check.stat.exists == false

    - name: Create current report
      shell: "es6-plato -r -d {{ci.reports_dir}}/{{ci.ref_name}} -t '{{ci.ref_author}} - {{ci.ref_message}}' ."
      args:
        chdir: "{{ci.build_dir}}"
