---
- hosts: localhost
  tasks:
    - name: Install NPM packages
      npm:
        path: "{{ ci.build_dir }}"
    - name: Build distribution
      shell: "webpack --config {{ ci.build_dir }}/webpack.prod.js --bail --display-error-details"
      args:
        chdir: "{{ ci.build_dir }}"
    - name: Create config.js
      copy:
        content: "{{ ci.files.configjs }}"
        dest: "{{ ci.build_dir }}/dist/config.js"
