- hosts: all:!localhost
  tasks:
    - name: Remove all versioned source files
      file:
        path: "{{ ci.deploy_dir }}/{{ item }}"
        state: absent
      with_items:
        - js
        - styles
    - name: Deploy distribution files
      copy:
        src: "{{ ci.build_dir }}/dist/"
        dest: "{{ ci.deploy_dir }}"
        owner: "{{ ci.deploy_owner }}"
        group: "{{ ci.deploy_owner_group }}"
        mode: "u+rwx,g+rx,o+rx,a+s"
